#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    automatic_update = true
    # install nerd fonts
    statusline_iseparator = "bar"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    statusline_unicode_symbols = true
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    project_rooter_outermost = false
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'
    filetree_direction = "left"
    enable_guicolor = true
    statusline_separator = 'slant'

# plugins
[[custom_plugins]]
  repo = 'kien/ctrlp.vim'
  merge = true

[[custom_plugins]]
  repo = 'prettier/vim-prettier'
  merge = true

[[custom_plugins]]
  repo = 'tpope/vim-surround'
  merge = true

[[custom_plugins]]
  repo = 'jiangmiao/auto-pairs'
  merge = true

[[custom_plugins]]
  repo = 'tpope/vim-fugitive'
  merge = true

[[custom_plugins]]
  repo = 'mattn/emmet-vim'
  merge = true

[[custom_plugins]]
  repo = 'vim-scripts/vim-gitgutter'
  merge = true

# themes
[[custom_plugins]]
  repo = "flazz/vim-colorschemes"
  merged = false

[[custom_plugins]]
  repo = "dracula/vim"
  name = "dracula"
  merged = false
# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'lang#javascript'

[[layers]]
name = 'lang#ruby'

[[layers]]
name = 'lang#c'
enable_clang_syntax_highlight = true

[[layers]]
name = 'lang#go'
